-- Database is expected to be DerbyDB, named evotingDB
-- user: "admin1", password: "admin1". Adjust as needed
CREATE TABLE tbl_candidate (pk_candidate_id bigint GENERATED BY DEFAULT AS IDENTITY, fld_surname varchar(50) NOT NULL, fld_name varchar(30) NOT NULL, fk_political_party_id integer NOT NULL, fk_electoral_periphery_id integer NOT NULL,PRIMARY KEY (pk_candidate_id));

CREATE TABLE tbl_electoral_periphery (pk_electoral_periphery_id integer GENERATED BY DEFAULT AS IDENTITY, fld_name varchar(100) NOT NULL, fld_registered_citizens_count integer, fld_seats_count integer NOT NULL, PRIMARY KEY (pk_electoral_periphery_id));

CREATE TABLE tbl_political_party (pk_party_id integer GENERATED BY DEFAULT AS IDENTITY, fld_title varchar(50) NOT NULL, fld_leaderFullName varchar(30) NOT NULL, PRIMARY KEY (pk_party_id));

CREATE TABLE tbl_vote (pk_vote_id bigint GENERATED BY DEFAULT AS IDENTITY, fld_is_invalid boolean NOT NULL, fld_is_blank boolean NOT NULL, fk_electoral_periphery_id integer NOT NULL, fk_political_party_id integer, fk_candidate_id bigint, PRIMARY KEY (pk_vote_id));

ALTER TABLE tbl_vote ADD CONSTRAINT FKtbl_vote800602 FOREIGN KEY (fk_candidate_id) REFERENCES tbl_candidate (pk_candidate_id);

ALTER TABLE tbl_vote ADD CONSTRAINT FKtbl_vote929198 FOREIGN KEY (fk_political_party_id) REFERENCES tbl_political_party (pk_party_id);

ALTER TABLE tbl_vote ADD CONSTRAINT FKtbl_vote92695 FOREIGN KEY (fk_electoral_periphery_id) REFERENCES tbl_electoral_periphery (pk_electoral_periphery_id);

ALTER TABLE tbl_candidate ADD CONSTRAINT FKtbl_candid239676 FOREIGN KEY (fk_political_party_id) REFERENCES tbl_political_party (pk_party_id);

ALTER TABLE tbl_candidate ADD CONSTRAINT FKtbl_candid233212 FOREIGN KEY (fk_electoral_periphery_id) REFERENCES tbl_electoral_periphery (pk_electoral_periphery_id);

INSERT INTO TBL_ELECTORAL_PERIPHERY (FLD_NAME, FLD_REGISTERED_CITIZENS_COUNT,FLD_SEATS_COUNT) VALUES
('Α΄ ΑΘΗΝΩΝ',467108,14),
('Β΄ ΑΘΗΝΩΝ',1511739,44),
('ΝΟΜΟΥ ΑΤΤΙΚΗΣ',499627,15),
('Α΄ ΠΕΙΡΑΙΩΣ',192841,6),
('Β΄ ΠΕΙΡΑΙΩΣ',272682,8),
('ΝΟΜΟΥ ΑΙΤΩΛΟΑΚΑΡΝΑΝΙΑΣ',252004,7),
('ΝΟΜΟΥ ΑΡΓΟΛΙΔΟΣ',95561,3),
('ΝΟΜΟΥ ΑΡΚΑΔΙΑΣ',105448,3),
('ΝΟΜΟΥ ΑΡΤΗΣ',86417,3),
('ΝΟΜΟΥ ΑΧΑΪΑΣ',291461,8),
('ΝΟΜΟΥ ΒΟΙΩΤΙΑΣ',115765,3),
('ΝΟΜΟΥ ΓΡΕΒΕΝΩΝ',41294,1),
('ΝΟΜΟΥ ΔΡΑΜΑΣ',108578,3),
('ΝΟΜΟΥ ΔΩΔΕΚΑΝΗΣΟΥ',167152,5),
('ΝΟΜΟΥ ΕΒΡΟΥ',146376,4),
('ΝΟΜΟΥ ΕΥΒΟΙΑΣ',210957,6),
('ΝΟΜΟΥ ΕΥΡΥΤΑΝΙΑΣ',30790,1),
('ΝΟΜΟΥ ΖΑΚΥΝΘΟΥ',38641,1),
('ΝΟΜΟΥ ΗΛΕΙΑΣ',182456,5),
('ΝΟΜΟΥ ΗΜΑΘΙΑΣ',144494,4),
('ΝΟΜΟΥ ΗΡΑΚΛΕΙΟΥ',279833,8),
('ΝΟΜΟΥ ΘΕΣΠΡΩΤΙΑΣ',51156,2),
('Α΄ ΘΕΣΣΑΛΟΝΙΚΗΣ',565162,16),
('Β΄ ΘΕΣΣΑΛΟΝΙΚΗΣ',313032,9),
('ΝΟΜΟΥ ΙΩΑΝΝΙΝΩΝ',171315,5),
('ΝΟΜΟΥ ΚΑΒΑΛΑΣ',139213,4),
('ΝΟΜΟΥ ΚΑΡΔΙΤΣΗΣ',142201,4),
('ΝΟΜΟΥ ΚΑΣΤΟΡΙΑΣ',51481,2),
('ΝΟΜΟΥ ΚΕΡΚΥΡΑΣ',101113,3),
('ΝΟΜΟΥ ΚΕΦΑΛΛΗΝΙΑΣ',41365,1),
('ΝΟΜΟΥ ΚΙΛΚΙΣ',98906,3),
('ΝΟΜΟΥ ΚΟΖΑΝΗΣ',160321,5),
('ΝΟΜΟΥ ΚΟΡΙΝΘΙΑΣ',140710,4),
('ΝΟΜΟΥ ΚΥΚΛΑΔΩΝ',124109,4),
('ΝΟΜΟΥ ΛΑΚΩΝΙΑΣ',93462,3),
('ΝΟΜΟΥ ΛΑΡΙΣΗΣ',275921,8),
('ΝΟΜΟΥ ΛΑΣΙΘΙΟΥ',72198,2),
('ΝΟΜΟΥ ΛΕΣΒΟΥ',101786,3),
('ΝΟΜΟΥ ΛΕΥΚΑΔΟΣ',26796,1),
('ΝΟΜΟΥ ΜΑΓΝΗΣΙΑΣ',189658,6),
('ΝΟΜΟΥ ΜΕΣΣΗΝΙΑΣ',175587,5),
('ΝΟΜΟΥ ΞΑΝΘΗΣ',110885,3),
('ΝΟΜΟΥ ΠΕΛΛΗΣ',151747,4),
('ΝΟΜΟΥ ΠΙΕΡΙΑΣ',129999,4),
('ΝΟΜΟΥ ΠΡΕΒΕΖΗΣ',65867,2),
('ΝΟΜΟΥ ΡΕΘΥΜΝΗΣ',79778,2),
('ΝΟΜΟΥ ΡΟΔΟΠΗΣ',108555,3),
('ΝΟΜΟΥ ΣΑΜΟΥ',42380,1),
('ΝΟΜΟΥ ΣΕΡΡΩΝ',214376,6),
('ΝΟΜΟΥ ΤΡΙΚΑΛΩΝ',150938,4),
('ΝΟΜΟΥ ΦΘΙΩΤΙΔΟΣ',165062,5),
('ΝΟΜΟΥ ΦΛΩΡΙΝΗΣ',56374,2),
('ΝΟΜΟΥ ΦΩΚΙΔΟΣ',44959,1),
('ΝΟΜΟΥ ΧΑΛΚΙΔΙΚΗΣ',108714,3),
('ΝΟΜΟΥ ΧΑΝΙΩΝ',142470,4),
('ΝΟΜΟΥ ΧΙΟΥ',53004,2);
