/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.akritikos.eelections.gui;

/**
 *
 * @author akritikos
 */
import info.akritikos.eelections.model.*;
import info.akritikos.eelections.utils.DataManager;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map.Entry;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.observablecollections.ObservableCollections;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

public class frmStatistic extends javax.swing.JFrame {

	/**
	 * Creates new form frmStatistic
	 */
	public frmStatistic() {
		initComponents();
	}

	public frmStatistic(frmElections parent) {
		this.parent = parent;
		dm = new DataManager();
		parties.addAll(dm.retrieveAll(PoliticalParty.class));
		peripheries.addAll(dm.retrieveAll(ElectoralPeriphery.class));
		peripheries.add(0, new ElectoralPeriphery("ΟΛΕΣ ΟΙ ΠΕΡΙΦΕΡΕΙΕΣ"));

		initComponents();
		model = (DefaultTableModel)tblData.getModel();
		init = true;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbPeriphery = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        pChart = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Εκλογική Περιφέρεια:");

        cmbPeriphery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${peripheries}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbPeriphery);
        bindingGroup.addBinding(jComboBoxBinding);

        cmbPeriphery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPeripheryItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbPeriphery, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPeriphery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Παράταξη", "Αριθμός Ψήφων", "Ποσοστό"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblData);

        pChart.setMinimumSize(new java.awt.Dimension(420, 380));
        pChart.setName(""); // NOI18N
        pChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnExit.setText("Έξοδος");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void cmbPeripheryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPeripheryItemStateChanged
		if (init && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			try {
				int rows = model.getRowCount();
				for (int i = rows - 1; i >= 0; i--) {
					model.removeRow(i);
				}
			} catch (Exception ex) {
				System.out.println(ex.getMessage());
			}
			LinkedHashMap<String, Integer> votes = new LinkedHashMap<>();
			ElectoralPeriphery per = peripheries.get(cmbPeriphery.getSelectedIndex());
			int totalVotes = 0;
			int selection = cmbPeriphery.getSelectedIndex();
			if (selection == 0) {
				for (ElectoralPeriphery pr : peripheries) {
					if (pr.getPkElectoralPeripheryId() != null) {
						totalVotes += pr.getFldRegisteredCitizensCount() / 1000;
					}
					int apoxi = totalVotes;
					parties.sort((p2, p1)-> {
						return p2.getVoteList().size() - p1.getVoteList().size();
					});
					parties.forEach(p-> {
						votes.put(p.getFldTitle(), p.getVoteList().size());
					});
					int akyra = dm.erroneousVotes(false, true, null, null);
					int leyka = dm.erroneousVotes(true, false, null, null);
					votes.put("Άκυρα", akyra);
					votes.put("Λευκά", leyka);
					for (Integer i : votes.values()) {
						apoxi -= i;
					}
					votes.put("Αποχή", apoxi);
				}
			} else {
				totalVotes = per.getFldRegisteredCitizensCount() / 1000;
				int apoxi = totalVotes;
				parties.sort((p1, p2)-> {
					return dm.countVotes(null, p2, per, PoliticalParty.class) - dm.countVotes(null, p1, per, PoliticalParty.class);
				});
				parties.forEach(p-> {
					int v = dm.countVotes(null, p, per, PoliticalParty.class);
					votes.put(p.getFldTitle(), v);
				});
				int akyra = dm.erroneousVotes(false, true, per, null);
				int leyka = dm.erroneousVotes(true, false, per, null);
				votes.put("Άκυρα", akyra);
				votes.put("Λευκά", leyka);
				for (Integer i : votes.values()) {
					apoxi -= i;
				}
				votes.put("Αποχή", apoxi);
			}
			DefaultPieDataset data = new DefaultPieDataset();
			for (Entry s : votes.entrySet()) {
				String name = s.getKey().toString();
				int val = Integer.parseInt(s.getValue().toString());
				float percent = totalVotes > 0 ? (float)val * 100 / totalVotes : 0;
				Vector row = new Vector();
				data.setValue(name, val);
				row.add(name);
				row.add(val);
				row.add(String.format("%.0f%%", percent));
				try {
					model.addRow(row);
				} catch (Exception ex) {
					System.out.println(ex.getMessage());
				}
			}
			try {
				pChart.remove(0);
			} catch (Exception ex) {

			}
			JFreeChart chart = ChartFactory.createPieChart(per.getFldName(), data, true, true, false);
			ChartPanel c = new ChartPanel(chart);
			pChart.add(c, 0);
			pChart.revalidate();
			pChart.repaint();
		}
	}//GEN-LAST:event_cmbPeripheryItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        parent.setVisible(true);
        parent.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmStatistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmStatistic().setVisible(true);
			}
		});
	}

	DefaultTableModel model;
	DataManager dm;
	List<ElectoralPeriphery> peripheries = ObservableCollections.observableList(new ArrayList<>());
	List<PoliticalParty> parties = ObservableCollections.observableList(new ArrayList<>());
	public List<ElectoralPeriphery> getPeripheries() {
		return peripheries;
	}
	private frmElections parent;
	boolean init = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cmbPeriphery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pChart;
    private javax.swing.JTable tblData;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
