/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.akritikos.eelections.gui;

import info.akritikos.eelections.contracts.IDBEntities;
import info.akritikos.eelections.model.*;
import info.akritikos.eelections.utils.DataManager;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import org.jdesktop.observablecollections.ObservableCollections;

/**
 *
 * @author akritikos
 */
public class pCandidateManagement extends javax.swing.JPanel {

	/**
	 * Creates new form pCandidateManagement
	 */
	public pCandidateManagement() {
		initComponents();
	}

	/**
	 * Gets populated lists from parent frame to speed up loading
	 * @param peripheries
	 * @param parties
	 * @param allCandidates
	 */
	public pCandidateManagement(List<ElectoralPeriphery> peripheries, List<PoliticalParty> parties,
								List<Candidate> allCandidates) {
		this.peripheries = peripheries;
		this.parties = parties;
		this.allCandidates = allCandidates;
		initComponents();
		dm = new DataManager();
	}

	/**
	 * On combo box selection changes, filters the corresponding records from
	 * allCandidates list and refreshes the list bound to tblCandidates
	 * @param evt
	 */
	private void filterChanged(java.awt.event.ItemEvent evt) {
		if (parties.isEmpty() || peripheries.isEmpty()) {
			return;
		}
		ElectoralPeriphery periphery = peripheries.get(cmbFilterPeriphery.getSelectedIndex());
		PoliticalParty party = parties.get(cmbFilterParty.getSelectedIndex());
		candidates.clear();
		//Predicate<Candidate> filter =
		//c->c.getFkPoliticalPartyId() == party && c.getFkElectoralPeripheryId() == periphery;
		try {
			candidates.addAll(
				allCandidates.stream().filter(c->Objects.equals(party.getPkPartyId(), c.getFkPoliticalPartyId().getPkPartyId()) &&
											  Objects.equals(c.getFkElectoralPeripheryId().getPkElectoralPeripheryId(), periphery.getPkElectoralPeripheryId())).collect(Collectors.toList())
			);
		} catch (Exception ex) {
			System.out.println(ex.getMessage());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

		jFilters = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		cmbFilterPeriphery = new javax.swing.JComboBox<>();
		cmbFilterParty = new javax.swing.JComboBox<>();
		jLabel2 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		btnDeleteAll = new javax.swing.JButton();
		btnDeleteOne = new javax.swing.JButton();
		btnSave = new javax.swing.JButton();
		btnAdd = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tblCandidates = new javax.swing.JTable();

		jLabel1.setText("Εκλογική Περιφέρεια:");

		cmbFilterPeriphery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${peripheries}");
		org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbFilterPeriphery);
		bindingGroup.addBinding(jComboBoxBinding);

		cmbFilterPeriphery.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cmbFilterPeripheryItemStateChanged(evt);
			}
		});

		cmbFilterParty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		eLProperty = org.jdesktop.beansbinding.ELProperty.create("${parties}");
		jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbFilterParty);
		bindingGroup.addBinding(jComboBoxBinding);

		cmbFilterParty.addItemListener(new java.awt.event.ItemListener() {
			public void itemStateChanged(java.awt.event.ItemEvent evt) {
				cmbFilterPartyItemStateChanged(evt);
			}
		});

		jLabel2.setText("Πολιτικό Κόμμα:");

		javax.swing.GroupLayout jFiltersLayout = new javax.swing.GroupLayout(jFilters);
		jFilters.setLayout(jFiltersLayout);
		jFiltersLayout.setHorizontalGroup(
			jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFiltersLayout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel1)
								.addComponent(jLabel2))
					  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					  .addGroup(jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(cmbFilterParty, 0, 176, Short.MAX_VALUE)
								.addComponent(cmbFilterPeriphery, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					  .addContainerGap())
		);
		jFiltersLayout.setVerticalGroup(
			jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jFiltersLayout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cmbFilterPeriphery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1))
					  .addGap(18, 18, 18)
					  .addGroup(jFiltersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(cmbFilterParty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel2))
					  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		btnDeleteAll.setText("Διαγραφή Όλων");
		btnDeleteAll.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnDeleteAllMouseClicked(evt);
			}
		});

		btnDeleteOne.setText("Διαγραφή Επιλεγμένων");
		btnDeleteOne.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnDeleteOneMouseClicked(evt);
			}
		});

		btnSave.setText("Αποθήκευση Όλων");
		btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnSaveMouseClicked(evt);
			}
		});

		btnAdd.setText("Προσθήκη Νέου");
		btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnAddMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup()
					  .addComponent(btnDeleteAll)
					  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					  .addComponent(btnDeleteOne)
					  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					  .addComponent(btnAdd)
					  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
					  .addComponent(btnSave)
					  .addContainerGap())
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel1Layout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(btnDeleteAll)
								.addComponent(btnDeleteOne)
								.addComponent(btnSave)
								.addComponent(btnAdd))
					  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
		);

		jLabel3.setText("Υποψήφιοι:");

		tblCandidates.setColumnSelectionAllowed(true);

		eLProperty = org.jdesktop.beansbinding.ELProperty.create("${candidates}");
		org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblCandidates);
		org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${pkCandidateId}"));
		columnBinding.setColumnName("Κωδικός");
		columnBinding.setColumnClass(Long.class);
		columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fldSurname}"));
		columnBinding.setColumnName("Επώνυμο");
		columnBinding.setColumnClass(String.class);
		columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fldName}"));
		columnBinding.setColumnName("Όνομα");
		columnBinding.setColumnClass(String.class);
		bindingGroup.addBinding(jTableBinding);
		jTableBinding.bind();
		jScrollPane1.setViewportView(tblCandidates);
		tblCandidates.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel2Layout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane1)
								.addGroup(jPanel2Layout.createSequentialGroup()
										  .addComponent(jLabel3)
										  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
		);
		jPanel2Layout.setVerticalGroup(
			jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(jPanel2Layout.createSequentialGroup()
					  .addContainerGap()
					  .addComponent(jLabel3)
					  .addGap(18, 18, 18)
					  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
					  .addContainerGap())
		);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jFilters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					  .addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					  .addContainerGap()
					  .addComponent(jFilters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					  .addGap(18, 18, 18)
					  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					  .addGap(18, 18, 18)
					  .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
					  .addContainerGap())
		);

		bindingGroup.bind();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * Null method, if the triggering event was an item selection, forward
	 * the event to the proper handler
	 * @param evt
	 */
	private void cmbFilterPeripheryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilterPeripheryItemStateChanged
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			filterChanged(evt);
		}
	}//GEN-LAST:event_cmbFilterPeripheryItemStateChanged

	/**
	 * Null method, if the triggering event was an item selection, forward
	 * the event to the proper handler
	 * @param evt
	 */
	private void cmbFilterPartyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilterPartyItemStateChanged
		if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
			filterChanged(evt);
		}
	}//GEN-LAST:event_cmbFilterPartyItemStateChanged

	/**
	 * Deletes all current candidates
	 * @param evt
	 */
	private void btnDeleteAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteAllMouseClicked
		List<Class<? extends IDBEntities>> types = new ArrayList<>();
		// Clear votes before deleting candidates
		types.add(Vote.class);
		types.add(Candidate.class);
		candidates.clear();
		dm.clearEntities(types);
	}//GEN-LAST:event_btnDeleteAllMouseClicked

	/**
	 * Deletes the currently selected candidate
	 * @param evt
	 */
	private void btnDeleteOneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteOneMouseClicked
		Candidate c = candidates.get(tblCandidates.getSelectedRow());
		candidates.remove(c);
		allCandidates.remove(c);
		Runnable delete = () -> {
			// Clear votes refering to the candidate to be deleted
			dm.massDelete(c.getVoteList());
			dm.delete(c);
		};
		new Thread(delete).start();
	}//GEN-LAST:event_btnDeleteOneMouseClicked

	/**
	 * Adds a new candidate to the list and passes focus to that entry on the
	 * name/surname since they haven't been edited after being added
	 * @param evt
	 */
	private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
		ElectoralPeriphery periphery = peripheries.get(cmbFilterPeriphery.getSelectedIndex());
		PoliticalParty party = parties.get(cmbFilterParty.getSelectedIndex());
		if (candidates.size() >= periphery.getFldSeatsCount()) {
			JOptionPane.showMessageDialog(this, "Η συγκεκριμένη περιφέρεια έχει το μέγιστο πλήθος επιτρεπόμενων υποψηφίων για αυτό το κόμμα!");
			return;
		}
		Candidate c = new Candidate("", "", periphery, party);
		candidates.add(c);
		tblCandidates.requestFocus();
		tblCandidates.editCellAt(candidates.size() - 1, 1);
	}//GEN-LAST:event_btnAddMouseClicked

	/**
	 * Saves all changes added to the table, ignores entries with null
	 * name/surname since they haven't been edited after being added
	 * @param evt
	 */
	private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
		Runnable save = () -> {
			dm.massSave(candidates);
		};
		new Thread(save).start();
	}//GEN-LAST:event_btnSaveMouseClicked

	// <editor-fold defaultstate="collapsed" desc="Fields">
	DataManager dm;
	private List<ElectoralPeriphery> peripheries = new ArrayList<>();
	private List<PoliticalParty> parties = new ArrayList<>();
	private final List<Candidate> candidates = ObservableCollections.observableList(new ArrayList<>());
	private List<Candidate> allCandidates = new ArrayList<>();
	// </editor-fold>

	// <editor-fold defaultstate="collapsed" desc="Binding properties">
	public List<ElectoralPeriphery> getPeripheries() {
		return peripheries;
	}
	public List<PoliticalParty> getParties() {
		return parties;
	}
	public List<Candidate> getCandidates() {
		return candidates;
	}
	// </editor-fold>

	// <editor-fold defaultstate="collapsed" desc="Internal fields">
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnAdd;
	private javax.swing.JButton btnDeleteAll;
	private javax.swing.JButton btnDeleteOne;
	private javax.swing.JButton btnSave;
	private javax.swing.JComboBox<String> cmbFilterParty;
	private javax.swing.JComboBox<String> cmbFilterPeriphery;
	private javax.swing.JPanel jFilters;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tblCandidates;
	private org.jdesktop.beansbinding.BindingGroup bindingGroup;
	// End of variables declaration//GEN-END:variables
	// </editor-fold>
}
