/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package info.akritikos.eelections.gui;

/**
 *
 * @author akritikos
 */
public class pElectionsSplash extends javax.swing.JPanel {

	/**
	 * Creates new form frmElections
	 */
	public pElectionsSplash() {
		initComponents();
	}



	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eap_small.png"))); // NOI18N
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jLabel2.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel2.setText("ΠΛΗ24 - eElections");

		jLabel3.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
		jLabel3.setText("Αλέξανδρος Κρητικός");

		jLabel4.setFont(new java.awt.Font("Cambria", 0, 36)); // NOI18N
		jLabel4.setText("2016-2017");

		jLabel5.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
		jLabel5.setText("Βασίλειος Κάκκος");

		jLabel6.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
		jLabel6.setText("Θωμάς Θεοχάρης");

		jLabel7.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
		jLabel7.setText("ΣΕΠ: Παναγιώτης Αλεφραγκής");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
					  .addContainerGap()
					  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										  .addGap(0, 0, Short.MAX_VALUE)
										  .addComponent(jLabel3)
										  .addGap(610, 610, 610))
								.addGroup(layout.createSequentialGroup()
										  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												  .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												  .addGroup(layout.createSequentialGroup()
														  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																  .addComponent(jLabel6)
																  .addComponent(jLabel5))
														  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																  .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
																  .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
										  .addContainerGap())))
			.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
					  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
					  .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
					  .addContainerGap())
		);
		layout.setVerticalGroup(
			layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout.createSequentialGroup()
					  .addContainerGap()
					  .addComponent(jLabel2)
					  .addGap(18, 18, 18)
					  .addComponent(jLabel1)
					  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
					  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										  .addComponent(jLabel4)
										  .addGap(18, 18, 18)
										  .addComponent(jLabel7)
										  .addContainerGap())
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										  .addComponent(jLabel3)
										  .addGap(18, 18, 18)
										  .addComponent(jLabel5)
										  .addGap(18, 18, 18)
										  .addComponent(jLabel6)
										  .addGap(31, 31, 31))))
		);
	}// </editor-fold>//GEN-END:initComponents


	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	// End of variables declaration//GEN-END:variables
}
